### ISSUE TITLE
abt error in clion bundled lldb

### ISSUE THREAD

**Issue by pkngpkng** [chriskohlhoff/asio-debugger-extensions#2]
https://github.com/chriskohlhoff/asio-debugger-extensions/blob/5ece4d040b1654c8208c246b16fc0f36f9c2a3da/lldb/awaitable_backtrace.py#L26

## error log

```text
(lldb) abt
Traceback (most recent call last):
  File "/Users/xxx/.lldb/scripts/awaitable_backtrace.py", line 44, in awaitable_backtrace
    walk_awaitable_frames(target, awaitable_frame)
  File "/Users/xxx/.lldb/scripts/awaitable_backtrace.py", line 35, in walk_awaitable_frames
    print_coro(target, frame.GetChildMemberWithName("coro_"), depth)
  File "/Users/xxx/.lldb/scripts/awaitable_backtrace.py", line 26, in print_coro
    address = coro_data.deref.GetValueAsAddress()
AttributeError: 'SBValue' object has no attribute 'GetValueAsAddress'
```

## fix it

fix it with: `address = int(coro_data.deref.GetValue(), base=16)`

## documents

* https://lldb.llvm.org/python_api/lldb.SBValue.html#lldb.SBValue

**Comment by pkngpkng** [comment]
https://github.com/chriskohlhoff/asio-debugger-extensions/pull/3

**Comment by pkngpkng** [comment]
@chriskohlhoff
